language: node_js
node_js:
  - "10.2.1"

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/
  keep-history: true
  on:
    branch: vue-migration

deploy:
  provider: script
  script: sh ./deploy.sh
  on:
    branch: master
