language: node_js
node_js:
  - "10.2.1"

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ce4ef0cc78171b15ddbf748b1db2dc146f671f80
  keep-history: true
  on:
    branch: vue-migration
