language: node_js
node_js:
  - "10.2.1"

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: e0d6e22a68afbc50c2298ee223110d09554189d6
  keep-history: true
